color0 #091518
color1 #ffb4ab
color2 #83d2e3
color3 #90d5af
color4 #71daa6
color5 #83d2e3
color6 #90d5af
color7 #d8e5e8
color8 #7c959b
color9 #ffb4ab
color10 #83d2e3
color11 #90d5af
color12 #71daa6
color13 #83d2e3
color14 #90d5af
color15 #d8e5e8

cursor                #d8e5e8
cursor_text_color     #091518
background            #091518
foreground            #d8e5e8
selection_foreground  #b1cbd1
selection_background  #334a50
url_color             #71daa6