[hooks]
# theme_mode_changed = "~/.config/noctalia/hooks/theme_mode_changed.sh"
# wallpaper_changed = "~/.config/noctalia/hooks/wallpaper_changed.sh"
# colors_changed = "~/.config/noctalia/hooks/colors_changed.sh"
