source completions/adb.nu
source completions/cargo.nu
source completions/curl.nu
source completions/fastboot.nu
source completions/flutter.nu
source completions/git.nu
source completions/godoc.nu
source completions/gradlew.nu
source completions/jj.nu
source completions/less.nu
source completions/make.nu
source completions/man.nu
source completions/mvn.nu
source completions/mysql.nu
source completions/npm.nu
source completions/pnpm.nu
source completions/podman.nu
source completions/rg.nu
source completions/rustup.nu
source completions/scoop.nu
source completions/ssh.nu
source completions/tar.nu
source completions/yarn-v4.nu
source completions/zig.nu
source completions/zoxide.nu
